---
editor_options: 
  markdown: 
    wrap: 72
---

# Cirriculum Vitea

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

Mijn naam is Anna en ik ben derdejaars bachelor student Life Sciences
aan de Hogeschool Utrecht met een specialisatie in Microbiologie en een
minor in Data Sciences. Ik ben sociaal, gemotiveerd en nieuwsgierig en
kijk er erg naar uit om praktijkervaring op te doen.

**Contactgegevens**

-   Naam: Anna van Donkersgoed

-   Mail: anna.vandonkersgoed\@student.hu.nl

**Talen**

-   Nederlands (moedertaal)

-   Engels

**Opleidingen**

| Jaar | Diploma | School | Plaats |
|----|----|----|----|
| 2020-heden | Life Sciences | Hogeschool Utrecht | Utrecht, Nederland |
| 2021 | propedeuse Life Scieces | Hogeschool Utrecht | Utrecht, Nederland |
| 2015 - 2020 | HAVO | Anna van Rijn college | Nieuwegein, Nederland |

**Technieken en vaardigheden**

-   MALDI-TOF PCR

-   Vitek Bacteriekweek + anaëroob kweken

-   MIC bepaling

-   Celkweek

-   NGS data verwerken

-   Metagenomics data verwerken

-   R

-   bash

-   Excel

**Project ervaringen**

Project Parodontitis

-   Onderzoek naar naar binding van Porphyromonas gingivalis aan
    verschillende oppervlakten (o.a. Streptococcus gordonii)

-   Effect van ijzer op bacteriële binding

-   Toepassing van anaërobe techieken (bactron600)

-   Ontwikkeling van flexibiliteit in onderzoeksaanpak

**Project Antimicrobiële resistentie**

-   Ontwikkeling van een bioinformatica pipeline voor analyse van
    antimicrobiële resistentie.

-   Data visualisatie d.m.v. een interactieve R Shiny app.

-   Toepassing van GitHub

-   Projectplanning en samenwerken in een Agile omgeving

**Werkervaring**

| Jaar | Functie | Bedrijf | Plaats |
|----|----|----|----|
| 2022 - 2024 | Horecamedewerker | DE KOM, stadstheater en kunstencentrum | Nieuwegein, Utrecht |
| 2021 - 2022 | Horecamedewerker | de Kraam | Nieuwegein, Utrecht |
| 2019 - 2021 | Vakkenvuller | Boon's mark | Makadocenter, Nieuwegein |

**Vrijwilligerswerk**

| Jaar | Vrijwilliger | Organisatie | Plaats |
|----|----|----|----|
| 2021 - heden | Leiding, leeftijd 7 tot 12 jaar | Scouting Jan van Hoof | Nieuwegein, Utrecht |
| 2019 - 2021 | Leiding, leeftijd 5 tot 7 jaar | Scouting Jan van Hoof | Nieuwegein, Nieuwegein |

**Competenties:**

-   Flexibel

-   Oplossingsgericht

-   Samenwerken

-   Organiseren
