# Looking ahead 

In 2 jaar zie ik mezelf werken voor een bedrijf wat microbiologie en datascience combineert. Het zou mij erg leuk lijken om onderzoeksvragen te beantwoorden doormiddel van zelf het onderzoek uit te voeren en daarna de verkregen data te verwerken op een reproduceerbare manier. Wat mij ook leuk lijkt is om programma's te gebruiken of aan programma's te werken die bepaalde bacteriën identificeren. Op dit moment gaat mijn interesse erg naar de bacteriën in het menselijke lichaam en vooral het maag-darm kanaal. 

Om dit doel te bereiken doe ik als specialisatie microbiologie en als minor datascience. Ook heb ik meer inzich gekregen in programmeren en het werken met bepaalde programma's die gebruikt worden voor data analyse. Ik heb zelf in december 2023 bij een lab gekeken om een idee te krijgen hoe de toekomst eruit kan zien. Hierdoor weet ik dat het me erg interessant lijkt. 

Er zijn veel skills die ik wil leren. Ik wil ervoor zorgen dat ik 3 programmeertalen ken: bash, R en python en dat ik soepel met deze talen kan werken. Daarnaast lijkt het me erg interessant om mij te verdiepen in bepaalde subgebieden van datascience zoals eiwit modulering, mutatie analyses en anitlichaam ontwerp. Ik wil deze skills aan het eind van mijn studie gehaald hebben of er al mee begonnen zijn. Dit wil ik bereiken door online veel informatie op te zoeken, data te downloaden en ermee te gaan oefenen. 

Ik wil gaan beginnen met mutatie analyses. Hiervoor ga ik eerst informatie opzoeken online en daarna kijken welke software er toegankelijk zijn om deze analyse uit te voeren. 
