# Vrije ruimte

DeepMicrobes is een programma wat de taxonomische classificatie bepaald door middel van deep learning. Taxonomische classificatie kan bijvoorbeeld door Kraken. Kraken heeft echter een taxonimische tree nodig om classificatie te kunnen uitvoeren. Als de species niet in de tree zitten dan kan Kraken ze niet identificeren. Om dit te omzeilen gebruikt DeepMicrobes een deep learning neural network om .. te trainen. #DeepMicrobes

DeepMicrobes is te downloaden via GitHub: [Klik hier om naar de Github pagina te gaan](https://github.com/MicrobeLab/DeepMicrobes)

Eerst ga ik het classificatie programma installeren en gebruiken op data.

Installatie volgens de github pagina:

```{r, eval = FALSE}
#Kloneer de repository van DeepMicrobes naar Rstudio 
git clone https://github.com/MicrobeLab/DeepMicrobes.git

#DeepMicrobes environment aanmakeneeeeeeeeeeeeee
conda env create -f DeepMicrobes/install.yml

```

Na het testen van DeepMicrobes worden er verschillende datasets gebruikt om te laten zien dat er mee gewerkt kan wordenL: De datasets die gebruikt worden:

Als laatst kijk ik naar of ik zelf een neural network kan trainen
